#!/bin/bash
## Uncomment  --clean lines only if you move your builds outside of $GDPATH/bin

GDPATH=""

function yes_or_no {
    while true; do
        read -rp "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;  
            [Nn]*) echo "Aborted" ; return  1 ;;
        esac
    done
}

function update_godot {
    scons platform=x11 use_llvm=yes builtin_openssl=yes mono_glue=no module_mono_enabled=yes &&
    mv $GDPATH/bin/godot.x11.tools.64.llvm $GDPATH/bin/godot &&
    chmod +x $GDPATH/bin/godot &&
    $GDPATH/bin/godot --generate-mono-glue modules/mono/glue &&
    scons platform=x11 use_llvm=yes builtin_openssl=yes mono_glue=yes module_mono_enabled=yes &&
    mv $GDPATH/bin/godot.x11.tools.64.llvm $GDPATH/bin/godot &&
    echo "Your update is ready in the godot/bin folder. Install at will."
}

function build_linux_targets {
    yes_or_no "Do you want to build export targets for Linux?" &&
    # scons --clean platform=x11 tools=no target=release bits=64 builtin_openssl=yes &&
    scons platform=x11 tools=no target=release bits=64 builtin_openssl=yes &&
    # scons --clean platform=x11 tools=no target=release_debug bits=64 builtin_openssl=yes &&
    scons platform=x11 tools=no target=release_debug bits=64 builtin_openssl=yes &&
    mv $GDPATH/bin/godot.x11.opt.64 $GDPATH/bin/linux_x11_64_release &&
    mv $GDPATH/bin/godot.x11.opt.debug.64 $GDPATH/bin/linux_x11_64_debug &&
    echo "Export targets for Linux/X11 are built."
}

function build_windows_targets {
    yes_or_no "Do you want to build targets for Windows?" &&
    # scons --clean platform=windows tools=no target=release bits=64 builtin_openssl=yes &&
    scons platform=windows tools=no target=release bits=64 builtin_openssl=yes &&
    # scons --clean platform=windows tools=no target=release_debug bits=64 builtin_openssl=yes &&
    scons platform=windows tools=no target=release_debug bits=64 builtin_openssl=yes &&
    mv $GDPATH/bin/godot.windows.opt.64.exe $GDPATH/bin/windows_64_release.exe &&
    mv $GDPATH/bin/godot.windows.opt.debug.64.exe $GDPATH/bin/windows_64_debug.exe &&
    echo "Export targets for Windows are built."
}

if [ -d $GDPATH ] 
then
    cd $GDPATH 
    git pull
    update_godot
    build_linux_targets
    build_windows_targets
else
    echo "$GDPATH does not exist"
    exit 1
fi

cd 
